Full Website for Math Magicians
mrsamsharma/Math-Magicians pull request #5
Opened 2022-12-05 19:27 UTC by mrsamsharma

- Used React Router to route three pages to create SPA
- Implement a good looking UI
- Separated Calculator Component for code quality

2022-12-05 20:04 UTC, gemmen29 requested changes
Hi @mrsamsharma, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 20:04 UTC, gemmen29 commented on src/App.js
>  // eslint-disable-next-line react/prefer-stateless-function
- [ ] Please remove the `eslint-disable` line as this defies the purpose of using linters in the first place.

2022-12-05 20:04 UTC, gemmen29 commented on src/components/Digit.js
> +// eslint-disable-next-line react/prop-types
- [ ] Please remove the `eslint-disable` line as this defies the purpose of using linters in the first place.

2022-12-05 20:04 UTC, gemmen29 commented on src/components/Navbar.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
- [ ] Please remove the `eslint-disable` line as this defies the purpose of using linters in the first place.

2022-12-05 20:04 UTC, gemmen29 commented on src/components/Operation.js
> +// eslint-disable-next-line react/prop-types
- [ ] Please remove the `eslint-disable` line as this defies the purpose of using linters in the first place.

2022-12-05 20:04 UTC, gemmen29 commented on src/index.js
> +// eslint-disable-next-line import/no-extraneous-dependencies
- [ ] Please remove the `eslint-disable` line as this defies the purpose of using linters in the first place.

2022-12-05 20:04 UTC, gemmen29 commented on src/pages/Calculator.js
> +// eslint-disable-next-line react/prefer-stateless-function
- [ ] Please remove the `eslint-disable` line as this defies the purpose of using linters in the first place.

2022-12-06 07:05 UTC, arslanbisharat approved these changes
Hi @mrsamsharma,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 07:14 UTC, merged